### ISSUE TITLE
I wanna add contributing.md

### ISSUE THREAD

**Issue by AyushSarode** [PriyankaBhattarai/Food-Valley#3]
Please label it as "Hacktoberfest-accepted"

**Comment by PriyankaBhattarai** [comment]
ok i giving you the task to add contributing.md file

**Comment by PriyankaBhattarai** [comment]
sorry but I already have the contributing.md file.

**Comment by AyushSarode** [comment]
I can improve it

**Comment by PriyankaBhattarai** [comment]
ok.

**Comment by AyushSarode** [comment]
If you like that you can add or close the issue

**Comment by PriyankaBhattarai** [comment]
Yaa sure best of luck
